title: "Dear First Year"
author: "Dear First Year"
email: "contact@dearfirstyear.com"
description: "A series of letters from current and graduated college students written to their first-year selves 
reflecting on their time in college and things they wish they had done differently."
baseurl: "/" 
url: "https://www.dearfirstyear.com" 
twitter_username: "dearfirstyear"
github_username:  "dearfirstyear"
future: false

# Build settings
plugins:
  - jekyll-feed

collections:
  posts:
    output: true 
    permalink: /:collection/:title

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
